# Generated by Django 3.2.8 on 2021-10-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('stock_Category_Name', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Stock_Category',
            },
        ),
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('part_Number', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('net_Cost_Each', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_Total_Sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('long_Description', models.TextField()),
                ('stock_Balance_Telford', models.IntegerField(blank=True, null=True)),
                ('stock_Balance_Notts', models.IntegerField()),
                ('stock_Level_Min', models.IntegerField()),
                ('stock_Level_Status', models.IntegerField()),
                ('stocked_At_Telford', models.BooleanField()),
                ('stocked_At_Notts', models.BooleanField()),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.branch')),
                ('stock_Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stockcategory')),
            ],
            options={
                'verbose_name_plural': 'Stock_Items',
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('stock_Location_Name', models.TextField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Stock_Location_Name',
            },
        ),
        migrations.CreateModel(
            name='StockManufacturer',
            fields=[
                ('stock_Manufacturer_Name', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Stock_Manufacturer',
            },
        ),
        migrations.CreateModel(
            name='StockOwner',
            fields=[
                ('stock_Owner_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Stock_Owner',
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_Date', models.DateField()),
                ('qty_Removed', models.IntegerField(blank=True, default=0)),
                ('qty_Added', models.IntegerField(blank=True, default=0)),
                ('added_Total', models.IntegerField(blank=True, default=0, null=True)),
                ('removed_Result', models.IntegerField(blank=True, default=0, null=True)),
                ('value_Removed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('calender_Info', models.TextField()),
                ('bran', models.IntegerField(blank=True, null=True)),
                ('branch_Location', models.CharField(choices=[('telford', 'Telford'), ('nottingham', 'Nottingham')], max_length=120)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.branch')),
                ('project_Number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('removed_By', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('stock_Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stockitems')),
            ],
            options={
                'verbose_name_plural': 'Stock_Log',
            },
        ),
        migrations.AddField(
            model_name='stockitems',
            name='stock_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='stock_Manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stockmanufacturer'),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='stock_Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stockowner'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('part_Number', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('description_Full', models.TextField(blank=True, null=True)),
                ('discount_Percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock_Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stockcategory')),
                ('stock_Manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stockmanufacturer')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
