# Generated by Django 3.2.8 on 2021-11-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockitems_net_cost_each'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='net_Cost_Each',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
