# Generated by Django 3.2.8 on 2021-10-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
        ('employee', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlsPanels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_Panel_Designation', models.CharField(max_length=120, null=True)),
                ('project_Description', models.CharField(max_length=120, null=True)),
                ('required_By_Date', models.DateField(blank=True, null=True)),
                ('drawings', models.FileField(upload_to='Control_Panel_Drawings_Upload/')),
                ('started', models.BooleanField(default=False, null=True)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('control_Panel_Calender_Label', models.TextField(blank=True, null=True)),
                ('late', models.BooleanField(default=False, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.branch')),
                ('build_Technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('project_Number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Control_Panels',
            },
        ),
        migrations.CreateModel(
            name='TestCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_Date', models.DateField(blank=True, null=True)),
                ('push_Buttons_Legends_Fitted', models.BooleanField(default=False, null=True)),
                ('voltage_Warning_Lables_Fitted', models.BooleanField(default=False, null=True)),
                ('earth_Bonding_To_Door_And_Enclosure', models.BooleanField(default=False, null=True)),
                ('earth_Bonding_Stickers_Fitted', models.BooleanField(default=False, null=True)),
                ('fuses_Fitted', models.BooleanField(default=False, null=True)),
                ('isolated_Shrouds_Fitted', models.BooleanField(default=False, null=True)),
                ('isolator_Handle_Operation_Tested', models.BooleanField(default=False, null=True)),
                ('rj45_Patch_Leads_Fitted', models.BooleanField(default=False, null=True)),
                ('earth_Continuity_1_or_Less', models.DecimalField(decimal_places=3, max_digits=3, null=True)),
                ('continuity_Of_Main_Conductors_L1_1_Or_Less', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('continuity_Of_Main_Conductors_L2_1_Or_Less', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('continuity_Of_Main_Conductors_L3_1_Or_Less', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('continuity_Of_Main_Conductors_N_1_Or_Less', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('Control_Panel_Voltage_Supply_Max_Rating_V', models.IntegerField(null=True)),
                ('Control_Voltage_Actual_Reading_V', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('supply_To_All_Devices_Checked', models.BooleanField(default=False, null=True)),
                ('safety_Relay_Functional_Test_Done', models.BooleanField(default=False, null=True)),
                ('indication_LEDs_Tested', models.BooleanField(default=False, null=True)),
                ('push_Buttons_Tested', models.BooleanField(default=False, null=True)),
                ('point_To_Point_Test_Completed', models.BooleanField(default=False, null=True)),
                ('termination_tug_Test_Completed', models.BooleanField(default=False, null=True)),
                ('inverters_Programmed', models.BooleanField(default=False, null=True)),
                ('plc_Program_Loaded', models.BooleanField(default=False, null=True)),
                ('tested_Stickers_Fitted', models.BooleanField(default=False, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('checked_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_By', to='employee.employee')),
                ('control_Panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_panel.controlspanels')),
                ('project_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('test_Engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_Engineer', to='employee.employee')),
            ],
        ),
    ]
