# Generated by Django 3.2.8 on 2021-10-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_Number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('order_Number', models.CharField(max_length=20)),
                ('order_Date', models.DateField(blank=True, null=True)),
                ('delivery_Date', models.DateField(blank=True, null=True)),
                ('completion_Date', models.DateField(blank=True, null=True)),
                ('started_Project', models.BooleanField()),
                ('installed_Delivered', models.BooleanField()),
                ('completed', models.BooleanField()),
                ('requires_Control_Panel', models.BooleanField()),
                ('reason_For_Hold', models.TextField(blank=True)),
                ('no_Description', models.TextField(blank=True)),
                ('payment_Stage_Added', models.BooleanField()),
                ('site_address_delivery', models.TextField(blank=True)),
                ('order_count', models.IntegerField()),
                ('project_Type', models.CharField(blank=True, choices=[('project', 'Project'), ('time and materials', 'Time and Materials')], max_length=20, null=True)),
                ('initial_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('install_Start', models.DateField(blank=True, null=True)),
                ('install_Finish', models.DateField(blank=True, null=True)),
                ('launch', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('days_To_Install', models.IntegerField(blank=True, null=True)),
                ('additional_Notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Project_Uploads/')),
                ('customer_Project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('project_Lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ResourceNames',
            fields=[
                ('resource_Names', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Resource_Names_Project_Tasks',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_Name', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Stage_Project_Tasks',
            },
        ),
        migrations.CreateModel(
            name='Stage_Payment_Description',
            fields=[
                ('stage_Payment_Description', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Stage_Payments_Descriptions',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('task_Type_Name', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Tasks_Project_Tasks',
            },
        ),
        migrations.CreateModel(
            name='WorkInstruction',
            fields=[
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_Increment', models.AutoField(primary_key=True, serialize=False)),
                ('start_Date_Time', models.CharField(blank=True, max_length=120, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Work_Instruction_File_Upload/')),
                ('site_Contact', models.CharField(blank=True, max_length=120, null=True)),
                ('site_Contact_Number', models.IntegerField(blank=True, null=True)),
                ('site_Address', models.TextField(blank=True, null=True)),
                ('site_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('work_Description', models.TextField(null=True)),
                ('materials_Requirement', models.TextField(blank=True, null=True)),
                ('additional_Information', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('project_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('technical_Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Work_Instructions',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('project_Description', models.CharField(blank=True, max_length=120, null=True)),
                ('task_Name', models.TextField(primary_key=True, serialize=False)),
                ('task_Added_On', models.DateField(null=True)),
                ('urgent_Task', models.BooleanField(default=False, null=True)),
                ('task_Completion_Target_Date', models.DateField(blank=True, null=True)),
                ('task_Done', models.BooleanField(default=False, null=True)),
                ('task_Completed_Date', models.DateField(blank=True, null=True)),
                ('project_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('task_Added_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_Added_By', to='employee.employee')),
                ('task_Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_Owner', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Stage_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_Percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('can_Be_Invoiced', models.BooleanField()),
                ('extra_Add_To_Order', models.BooleanField(blank=True, null=True)),
                ('extra_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra_Description', models.TextField(blank=True, null=True)),
                ('new_Order_No', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_Invoiced_And_Done', models.BooleanField()),
                ('customer_Order', models.FileField(blank=True, null=True, upload_to='Customer_Uploads/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_Of_Invoice', models.DateField()),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('stage_Authorised_By', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('stage_Payment_Description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.stage_payment_description')),
            ],
            options={
                'verbose_name_plural': 'Stage_Payments',
            },
        ),
        migrations.CreateModel(
            name='SiteReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_Date', models.DateField(null=True)),
                ('site', models.CharField(blank=True, max_length=120, null=True)),
                ('machine_equipment', models.CharField(max_length=120, null=True)),
                ('actions_Observations', models.TextField(blank=True, null=True)),
                ('advisory', models.TextField(blank=True, null=True)),
                ('attach_Data_File', models.FileField(blank=True, null=True, upload_to='Site_Reports_Uploads/')),
                ('time_Of_Arrival', models.TimeField(blank=True, null=True)),
                ('time_Of_Departure', models.TimeField(blank=True, null=True)),
                ('travel_To_From_Site_Hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mileage_Total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('hcs_Engineer_Sign', models.TextField(blank=True, null=True)),
                ('client_Representative_Full_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('client_Representative_Phone', models.IntegerField(blank=True, null=True)),
                ('client_Representative_Sign', models.TextField(blank=True, null=True)),
                ('invoice_Possible', models.BooleanField(null=True)),
                ('processed_By_Office', models.BooleanField(null=True)),
                ('processed_By_Office_Date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('hcs_Engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('project_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Site_Reports',
            },
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(null=True)),
                ('start_Date', models.DateField(blank=True, null=True)),
                ('finish_Date', models.DateField(blank=True, null=True)),
                ('percent_Complete', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('project_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('resource_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.resourcenames')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.stage')),
                ('task_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.tasktype')),
            ],
            options={
                'verbose_name_plural': 'Project_Tasks',
            },
        ),
        migrations.CreateModel(
            name='Project_Milestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=50)),
                ('milestone_Date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Project_Milestones',
            },
        ),
    ]
