# Generated by Django 3.2.8 on 2021-11-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_initial_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_Order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
