# Generated by Django 3.2.8 on 2021-11-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20211111_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttasks',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttasks',
            name='percent_Complete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
