# Generated by Django 3.2.8 on 2021-10-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branchs',
            },
        ),
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('auto_increment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_1', models.IntegerField(blank=True, null=True)),
                ('phone_2', models.IntegerField(blank=True, null=True)),
                ('skill_Set', models.TextField(blank=True, null=True)),
                ('detailed_information', models.TextField(blank=True, null=True)),
                ('data_File', models.FileField(blank=True, null=True, upload_to='Contractors_File_Uploads/')),
                ('approve', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contractors',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('position', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('contracted_start_time', models.TimeField()),
                ('contracted_finish_time', models.TimeField()),
                ('branch_location', models.CharField(max_length=120)),
                ('account', models.CharField(max_length=120)),
                ('standard_hours', models.IntegerField(blank=True, null=True)),
                ('annual_Allowance', models.IntegerField(blank=True, null=True)),
                ('annual_Allowance_remaining', models.IntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='AssetRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_Description', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_Number', models.CharField(blank=True, max_length=120, null=True)),
                ('date_Of_Issue', models.DateField(blank=True, null=True)),
                ('text_formula', models.CharField(blank=True, max_length=120, null=True)),
                ('tool_Owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'AssetRegister',
            },
        ),
    ]
