# Generated by Django 3.2.8 on 2021-12-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_schedule_time_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time_Type',
            new_name='TimeType',
        ),
    ]
