# Generated by Django 3.2.8 on 2021-12-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20211206_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.timetype'),
        ),
    ]
