# Generated by Django 3.2.8 on 2021-12-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_schedule_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='holiday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='reason',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
