# Generated by Django 3.2.8 on 2021-10-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('project', '0001_initial'),
        ('stock', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominalCode',
            fields=[
                ('result', models.CharField(max_length=50, null=True)),
                ('nominal_Code_No', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='Description', max_length=50)),
                ('budget_Allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('over_Budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost_Centre_Managers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Nominal_Codes',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('suppliers_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('primary_Contact_Sales', models.CharField(max_length=50)),
                ('primary_Contact_Admin', models.CharField(max_length=50)),
                ('primary_Contact_Technical', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_Number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('line_Item_Count', models.IntegerField(blank=True, null=True)),
                ('order_Number_Unique_ID', models.CharField(default='0', max_length=15)),
                ('order_Date', models.DateField(null=True)),
                ('delivery_Required_Date', models.DateField(null=True)),
                ('delivered_In_Full', models.BooleanField(default=False)),
                ('partial_Delivery', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('delivery_Address', models.TextField(blank=True, null=True)),
                ('order_Value_Total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_Delivery_Date', models.DateField(blank=True, null=True)),
                ('terms', models.CharField(blank=True, max_length=120, null=True)),
                ('sales_Tax', models.DecimalField(decimal_places=3, default=0.2, max_digits=4)),
                ('shipping_Handling', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('receipt_PDF', models.FileField(blank=True, null=True, upload_to='Purchase_Order_Receipt_PDF/')),
                ('completed_Date', models.DateField(blank=True, null=True)),
                ('delivered_To', models.CharField(choices=[('Telford', 'Telford'), ('Nottingham', 'Nottingham'), ('other', 'other')], default='Telford', max_length=50)),
                ('fao', models.CharField(blank=True, max_length=120, null=True)),
                ('order_Notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.branch')),
                ('checked_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('order_Placed_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_placed_by', to='employee.employee')),
                ('project_Number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('requisitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitioner', to='employee.employee')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.suppliers')),
            ],
            options={
                'verbose_name_plural': 'Purchase_Orders',
            },
        ),
        migrations.CreateModel(
            name='POLineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_Number', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('net_Cost_Each_ExVAT', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('line_Total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('part_Number', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(default='Description')),
                ('arrived', models.BooleanField(default=False)),
                ('qty_Arrived', models.IntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.products')),
                ('purchase_Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.purchaseorder')),
                ('stock_Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.stockitems')),
            ],
            options={
                'verbose_name_plural': 'PO_Line_Items',
            },
        ),
        migrations.CreateModel(
            name='po_WithoutProjects',
            fields=[
                ('po_Number', models.CharField(default='HCS', max_length=120)),
                ('inc_Number', models.AutoField(primary_key=True, serialize=False)),
                ('date_Of_PO', models.DateField(blank=True, null=True)),
                ('details', models.CharField(default='Details', max_length=120)),
                ('authorised_By', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorised_By', to='employee.employee')),
                ('nominal_Code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.nominalcode')),
                ('order_Placed_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_Placed_By', to='employee.employee')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.suppliers')),
            ],
            options={
                'verbose_name_plural': 'PO_Without_Projects',
            },
        ),
    ]
