# Generated by Django 3.2.8 on 2021-11-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_auto_20211028_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='primary_Contact_Admin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='primary_Contact_Sales',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='primary_Contact_Technical',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
