# Generated by Django 3.2.8 on 2021-11-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_auto_20211101_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_Number_Unique_ID',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
