# Generated by Django 3.2.8 on 2021-11-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockitems_net_cost_each'),
        ('purchase_order', '0010_alter_purchaseorder_sales_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polineitems',
            name='arrived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='polineitems',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AlterField(
            model_name='polineitems',
            name='line_Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='polineitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.products'),
        ),
        migrations.AlterField(
            model_name='polineitems',
            name='qty_Arrived',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='polineitems',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
