# Generated by Django 3.2.8 on 2021-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0011_auto_20211111_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polineitems',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
    ]
