# Generated by Django 3.2.8 on 2021-10-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LACQuotePortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=120)),
                ('lac_reference', models.CharField(max_length=120)),
                ('lac_description', models.TextField()),
                ('category_Of_Quote', models.CharField(choices=[('Cat A', 'Cat A'), ('Cat B', 'Cat B'), ('Cat C', 'Cat C')], max_length=10)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='LAC_Quote_Portal/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='LAC_Quote_Portal/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='LAC_Quote_Portal/')),
                ('status', models.CharField(choices=[('awaiting reply', 'Awaiting Reply'), ('in progress', 'In Progress'), ('quotation submitted', 'Quotation Submitted')], max_length=120)),
                ('date_Of_Request', models.DateField(blank=True, null=True)),
                ('quote_Required_By', models.DateField()),
                ('date_Of_Completion', models.DateField(blank=True, null=True)),
                ('general_Details', models.TextField(blank=True, null=True)),
                ('motor_Control_details', models.TextField(blank=True, null=True)),
                ('pneumatics_Required', models.BooleanField(null=True)),
                ('wms_Interface_Required', models.BooleanField()),
                ('barcode_Reading_Required', models.BooleanField()),
                ('location_Within_Uk_Overseas', models.CharField(max_length=120)),
                ('installation_Required', models.BooleanField()),
                ('description_Header', models.TextField()),
                ('lac_Sales_Person', models.CharField(blank=True, max_length=120, null=True)),
                ('holloway_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('holloway_Contact_connection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'LAC_Quote_Portal',
            },
        ),
        migrations.CreateModel(
            name='LACSalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'LAC_Sales_Teams',
            },
        ),
        migrations.CreateModel(
            name='QuoteNumbers',
            fields=[
                ('QuoteNo', models.CharField(max_length=10)),
                ('quote_No_Inc', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quote_Date', models.DateField()),
                ('quote_Description', models.TextField()),
                ('recipient_Name', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quote_Prepared_By', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('lac_Quote_Portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LAC.lacquoteportal')),
            ],
        ),
        migrations.AddField(
            model_name='lacquoteportal',
            name='quote_Requested_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LAC.lacsalesteam'),
        ),
    ]
