# Generated by Django 3.2.8 on 2021-10-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
        ('purchase_order', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMType',
            fields=[
                ('bom_Type', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'BOM_Type_List',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('sub_Section_Name', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'BOM_Sub_Sections',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('item_Number', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('total_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('order_Number_Unique_ID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('delivery_Date', models.DateField(blank=True, null=True)),
                ('bom_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BOM.bomtype')),
                ('project_Number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('sub_Section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BOM.subsection')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.suppliers')),
            ],
            options={
                'verbose_name_plural': 'BOMs',
            },
        ),
    ]
