# Generated by Django 3.2.8 on 2021-11-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20211029_1021'),
        ('BOM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='item_Number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.stockitems'),
        ),
    ]
