# Generated by Django 3.2.8 on 2021-11-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0003_alter_bom_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
