# Generated by Django 3.2.8 on 2021-11-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_initial_value'),
        ('BOM', '0005_alter_bom_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='order_Number_Unique_ID',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='bom',
            name='project_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='project.project'),
        ),
    ]
