# Generated by Django 3.2.8 on 2021-11-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_initial_value'),
        ('BOM', '0006_auto_20211101_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bom',
            name='project_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project'),
        ),
    ]
