# Generated by Django 3.2.8 on 2021-11-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0007_auto_20211101_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
