# Generated by Django 3.2.8 on 2021-11-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_initial_value'),
        ('BOM', '0009_bomtype_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='project_Number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project'),
        ),
    ]
