# Generated by Django 3.2.8 on 2021-11-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0010_subsection_project_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='project_Number',
        ),
    ]
