# Generated by Django 3.2.8 on 2021-11-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_auto_20211101_0947'),
        ('BOM', '0011_remove_subsection_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.suppliers'),
        ),
    ]
