# Generated by Django 3.2.8 on 2021-10-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('auto_Increment', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(null=True)),
                ('start_Time', models.TimeField(null=True)),
                ('end_Time', models.TimeField(null=True)),
                ('notes', models.TextField(null=True)),
                ('weekend', models.IntegerField(choices=[(1, 1), (0, 0)], null=True)),
                ('flag', models.BooleanField(default=False, null=True)),
                ('holiday', models.BooleanField(default=False, null=True)),
                ('base_Time', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('result_Time', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('day_Of_Week', models.IntegerField(blank=True, null=True)),
                ('overnight', models.BooleanField(default=False, null=True)),
                ('aux_Name', models.CharField(default='temp', max_length=120, null=True)),
                ('display', models.CharField(default='temp', max_length=120, null=True)),
                ('overtime_Weekday', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('employee', models.CharField(blank=True, max_length=120, null=True)),
                ('employee_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('project_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project')),
            ],
            options={
                'verbose_name_plural': 'TimeLogs',
            },
        ),
    ]
